### ISSUE TITLE
Could not connect heroku database

### ISSUE THREAD

**Issue by Atiladanvi** [lebalz/db-sql#49]
The heroku host could not able to give access to db-sql

**Comment by lebalz** [comment]
Hi Atiladanvi
Could you establish a connection to your heroku database host but you couldn't see your databases? Or was the connection to the heroku server already failing?

**Comment by Atiladanvi** [comment]
The service try connect the database "postgres" by default and could not connect my specific database. The error messages says: you don't have permission to access the "postgres" database. But the heroku not give permission to acces the  "postgres" database.
![image](https://user-images.githubusercontent.com/11599205/82236444-7c28e900-990a-11ea-8333-c35c81fa09c5.png)

**Comment by lebalz** [comment]
@Atiladanvi now you should be able to connect to heroku databases by setting the initial database yourself.

**Comment by Atiladanvi** [comment]
Great ! Nice !
